#!/usr/bin/env bash
# vim: set filetype=sh

# Return if not running interactive bash.
if [ -z "${BASH_VERSION:-}" ] || [ -z "${PS1:-}" ]; then
    return
fi

# Load $HOME/.bashrc if exists.
function bashrc::load_bashrc_if_exists()
{
    local readonly bashrc_file="${HOME}/.bashrc"
    if test -r "${bashrc_file}"; then
        source "${bashrc_file}"
    fi
}

bashrc::load_bashrc_if_exists
