#!/usr/bin/env bash
# vim: set filetype=sh

# Return if not running interactive bash.
if [ -z "${BASH_VERSION:-}" ] || [ -z "${PS1:-}" ]; then
    return
fi

# Include .bashrc if exists.
bashrc_file="${HOME}/.bashrc"
if [ -f "${bashrc_file}" ]; then
    source "${bashrc_file}"
fi
unset bashrc_file
