#!/usr/bin/env bash

# Bash Configuration when Login Shell.
#
# When Bash is invoked as an interactive login shell,
# or as a non-interactive shell with the --login option.
#
# @link https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

# Return if not running interactive bash.
if [[ "${BASH_VERSION:-}" == "" ]] || [[ "${PS1:-}" == "" ]]; then
  return
fi
