#!/usr/bin/env bash
# vim: set filetype=sh

# Source files in bash directory.
bash_directory="$HOME/.bash"
if [ -d "$bash_directory" ]; then
    # Source functions first.
    source "$bash_directory/bash_functions"

    # Source exports and aliases.
    source_file_if_exists "$bash_directory/bash_exports"
    source_file_if_exists "$bash_directory/bash_aliases"

    # Source completions
    source_files_in_directory_if_exists "$bash_directory/completions"

    # Source prompts
    source_file_if_exists "$bash_directory/prompts/git-prompt.sh"
fi;
unset bash_directory
