#!/usr/bin/env bash
# vim: set filetype=sh

# Source files in bash directory.
bash_directory="$HOME/.bash"
if [ -d "$bash_directory" ]; then
    # Source functions first.
    source "$bash_directory/rc/functions"

    # Source completions
    source_files_in_directory_if_exists "$bash_directory/completions"

    # Source prompts
    source_file_if_exists "$bash_directory/prompts/git-prompt.sh"

    # Source files in 'rc' directory
    source_files_in_directory_if_exists "$bash_directory/rc"

    # Source files in 'rc.os' by OS
    source_files_in_directory_if_exists "$bash_directory/rc.os/$(uname -s)"

    # Source files in 'rc.host' by HOSTNAME
    source_file_if_exists "$bash_directory/rc.host/$HOSTNAME"

    # Source fzf files
    source_file_if_exists "$HOME/.fzf.bash"
fi;
unset bash_directory

# Include .bashrc_local if it exists.
bashrc_file="$HOME/.bashrc_local"
if [ -f "$bashrc_file" ]; then
    source "$bashrc_file"
fi
unset bashrc_file

# Run ssh-agent automatically.
if [ -z "$SSH_AGENT_PID" ] && [ -z "$TMUX" ]; then
    ssh-agent -s
fi
