#!/usr/bin/env bash
# vim: set filetype=sh

export GOPATH="$HOME/workspace/go"
export PATH="$GOPATH/bin:$PATH"

export WORKON_HOME="$HOME/.virtualenvs"
export PATH="$HOME/workspace/Arcanist/arcanist/bin:$PATH"
