#!/usr/bin/env bash
# vim: set filetype=sh

# Change directory quickly.
alias ..="cd .."
alias ...="cd ../.."
alias cd..="cd .."
alias cd...="cd ../.."
alias cd-="cd -"

# Shorten commands.
alias c="clear"
alias cls="clear"
alias d="dir"
alias f="finger"
alias h="history"
alias l="last"
alias lo="logout"
alias um="unmount"
alias s="screen"
alias so="source"
alias t="telnet"
alias cps="composer"

# List directory contents with colorized output.
#   -G        | Enable colorized output.
#   -F        | Display a slash ('/') immediately after each pathname that is a directory,
#             | an asterisk ('*') after each that is executable,
#             | an at sign ('@') after each symbolic link,
#             | an equals sign ('=') after each socket,
#             | a percent sign ('%') after each whiteout,
#             | and a vertical bar ('|') after each that is a FIFO.
#   -d        | Directories are listed as plain files (not searched recursively).
#   -1        | Force output to be one entry per line.
#   -A        | Include directory entries whose names begin with a dot ('.').
#   -l        | List files in the long format.
#   -D format | When printing in the long (-l) format, use format to format the date and time output.
case $(uname -s) in
    "FreeBSD" | "Darwin")
        alias ls="ls -GF"
        alias l.="ls -GF -d .*"                 # List hidden files only.
        alias l1="ls -GF1"                      # Force output to be one entry per line.
        alias la="ls -GFA"                      # List all files.
        alias ll="ls -GFl -D '%Y-%m-%d %T'"     # List files in the long format.
        alias lla="ls -GFlA -D '%Y-%m-%d %T'"   # List all files in the long format.
        ;;
    "Linux")
        # TODO Add aliases for ls in Linux
        ;;
esac

# Be careful with copy files.
#   -i | Cause cp to write a prompt to the standard error output befor copying a file
#      | that would overwrite an existing file.
alias copy="cp -i"

# Be careful with move and rename files.
#   -i | Cause mv to write a prompt to standard error before moving a file
#      | that would overwrite an existing file.
alias move="mv -i"

# Be careful with remove files
#   -i | Request confirmation before attempting to remove each file.
alias remove="rm -i"
