#!/usr/bin/env bash
# vim: set filetype=sh

# Change directory quickly.
alias ..="cd .."
alias ...="cd ../.."
alias cd..="cd .."
alias cd...="cd ../.."
alias cd-="cd -"

# Shorten commands.
alias c="clear"
alias cls="clear"
alias d="dir"
alias f="finger"
alias h="history"
alias l="last"
alias lo="logout"
alias um="unmount"
alias s="screen"
alias so="source"
alias t="telnet"
alias cps="composer"
